<script lang="ts">
  import { getDiary, lifeContentAccess, lifePeople, lifeSetContentVisibility, lifeSetDiaryVisibility, lifeSetFriend, lifeView, listDiaryDates, type LifePerson } from '../api';
  import { getTheme, setTheme, type ThemeMode, type ThemeSkin } from '../theme';
  let people=$state<LifePerson[]>([]),error=$state('');
  let visibility=$state<'private'|'friends'|'public'>((localStorage.getItem('life-diary-visibility') as any)||'private'),sharing=$state(false);
  async function load(){try{people=(await lifePeople()).people;const view=await lifeView();visibility=(await lifeContentAccess(view.me.my_life_id)).features.diary.visibility}catch(e){error=`${e}`}}load();
  async function toggle(person:LifePerson){await lifeSetFriend(person.agent_id,!person.is_friend);await load()}
  async function setVisibility(next:typeof visibility){sharing=true;error='';try{await lifeSetContentVisibility('diary',next);if(next!=='private'){const dates=await listDiaryDates();await Promise.all(dates.map(async date=>lifeSetDiaryVisibility(date,await getDiary(date)||'',next)))}visibility=next;localStorage.setItem('life-diary-visibility',next)}catch(e){error=`${e}`}finally{sharing=false}}
  let themeMode=$state<ThemeMode>(getTheme().mode),themeSkin=$state<ThemeSkin>(getTheme().skin);
  const MODES:[ThemeMode,string][]=[['light','라이트'],['dark','다크'],['system','시스템']];
  const SKINS:{id:ThemeSkin;label:string;dot:string}[]=[{id:'sky',label:'하늘',dot:'#84c9ef'},{id:'mint',label:'민트',dot:'#5cd0b0'},{id:'peach',label:'살구',dot:'#f4b183'},{id:'lavender',label:'라벤더',dot:'#b9a6f0'}];
  function pickMode(m:ThemeMode){themeMode=m;setTheme({mode:m,skin:themeSkin})}
  function pickSkin(s:ThemeSkin){themeSkin=s;setTheme({mode:themeMode,skin:s})}
</script>
<section><h2>테마</h2><p>밝기</p><nav class="seg">{#each MODES as opt}<button class:active={themeMode===opt[0]} onclick={()=>pickMode(opt[0])}>{opt[1]}</button>{/each}</nav><p>색상 세트</p><div class="skins">{#each SKINS as s (s.id)}<button class="swatch" class:active={themeSkin===s.id} onclick={()=>pickSkin(s.id)} title={s.label}><span class="dot" style="background:{s.dot}"></span>{s.label}</button>{/each}</div><hr/><h2>일촌 관리</h2><p>내가 일촌공개로 설정한 콘텐츠를 볼 수 있는 사람을 관리합니다.</p><div>{#each people as person (person.agent_id)}<label><span>{person.name}</span><input type="checkbox" checked={person.is_friend} onchange={()=>toggle(person)}/></label>{:else}<p>등록된 다른 사용자가 없어요.</p>{/each}</div><hr/><h2>다이어리 공개 범위</h2><p>비공개가 기본이며, 공개를 선택한 경우에만 다이어리가 Life 서버로 전송됩니다.</p><nav>{#each [['private','비공개'],['friends','일촌공개'],['public','전체공개']] as option}<button class:active={visibility===option[0]} disabled={sharing} onclick={()=>setVisibility(option[0] as typeof visibility)}>{option[1]}</button>{/each}</nav>{#if error}<p class="error">{error}</p>{/if}</section>
<style>section{padding:18px}h2{margin:0 0 5px;font-size:16px}section>p{color:var(--text-soft);font-size:12px}section>div{display:grid;grid-template-columns:repeat(2,1fr);gap:8px;margin-top:14px}label{display:flex;justify-content:space-between;padding:10px 12px;background:var(--cream);color:var(--cream-ink);border-radius:9px}nav{display:flex;gap:7px;margin-top:12px}button{border:0;border-radius:99px;padding:7px 12px;background:var(--lav-surface);color:var(--lav-ink);cursor:pointer}button.active{background:var(--accent);color:var(--accent-ink)}hr{border:0;border-top:1px solid var(--line);margin:20px 0}.error{color:var(--danger)}.seg{display:inline-flex;border:1px solid var(--line);border-radius:9px;overflow:hidden;margin-top:6px}.seg button{border:0;border-right:1px solid var(--line);border-radius:0;background:transparent;color:var(--text);padding:7px 16px}.seg button:last-child{border-right:0}.seg button.active{background:var(--accent);color:var(--accent-ink);font-weight:700}.skins{display:flex;gap:10px;flex-wrap:wrap;margin-top:6px}.swatch{display:flex;align-items:center;gap:6px;border:1px solid var(--line);background:var(--surface-inset);color:var(--text);border-radius:99px;padding:5px 12px 5px 6px}.swatch.active{border-color:var(--accent-strong);font-weight:700}.swatch .dot{width:16px;height:16px;border-radius:50%;border:1px solid var(--line)}</style>
