<script lang="ts">
  import { getDiary, lifeContentAccess, lifePeople, lifeSetContentVisibility, lifeSetDiaryVisibility, lifeSetFriend, lifeView, listDiaryDates, type LifePerson } from '../api';
  let people=$state<LifePerson[]>([]),error=$state('');
  let visibility=$state<'private'|'friends'|'public'>((localStorage.getItem('life-diary-visibility') as any)||'private'),sharing=$state(false);
  async function load(){try{people=(await lifePeople()).people;const view=await lifeView();visibility=(await lifeContentAccess(view.me.my_life_id)).features.diary.visibility}catch(e){error=`${e}`}}load();
  async function toggle(person:LifePerson){await lifeSetFriend(person.agent_id,!person.is_friend);await load()}
  async function setVisibility(next:typeof visibility){sharing=true;error='';try{await lifeSetContentVisibility('diary',next);if(next!=='private'){const dates=await listDiaryDates();await Promise.all(dates.map(async date=>lifeSetDiaryVisibility(date,await getDiary(date)||'',next)))}visibility=next;localStorage.setItem('life-diary-visibility',next)}catch(e){error=`${e}`}finally{sharing=false}}
</script>
<section><h2>일촌 관리</h2><p>내가 일촌공개로 설정한 콘텐츠를 볼 수 있는 사람을 관리합니다.</p><div>{#each people as person (person.agent_id)}<label><span>{person.name}</span><input type="checkbox" checked={person.is_friend} onchange={()=>toggle(person)}/></label>{:else}<p>등록된 다른 사용자가 없어요.</p>{/each}</div><hr/><h2>다이어리 공개 범위</h2><p>비공개가 기본이며, 공개를 선택한 경우에만 다이어리가 Life 서버로 전송됩니다.</p><nav>{#each [['private','비공개'],['friends','일촌공개'],['public','전체공개']] as option}<button class:active={visibility===option[0]} disabled={sharing} onclick={()=>setVisibility(option[0] as typeof visibility)}>{option[1]}</button>{/each}</nav>{#if error}<p class="error">{error}</p>{/if}</section>
<style>section{padding:18px}h2{margin:0 0 5px;font-size:16px}section>p{color:var(--ink-soft);font-size:12px}section>div{display:grid;grid-template-columns:repeat(2,1fr);gap:8px;margin-top:14px}label{display:flex;justify-content:space-between;padding:10px 12px;background:var(--pastel-cream);border-radius:9px}nav{display:flex;gap:7px;margin-top:12px}button{border:0;border-radius:99px;padding:7px 12px;background:var(--pastel-lav);cursor:pointer}button.active{background:var(--accent);color:white}hr{border:0;border-top:1px solid var(--pastel-lav);margin:20px 0}.error{color:#b74444}</style>
